server:
  port: 8081
  servlet:
    context-path: /swagger2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  rabbitmq:
    addresses: 192.168.0.1:5672
    username: guest
    password: pwd
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        prefetch: 1
        max-concurrency: 10


swagger2:
  enable: true

missyou:
  api-package: com.lin.eshopping.api

